In [3]:
import numpy
n=numpy.arange(27)

In [4]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [7]:
m = numpy.asarray([[123,12,123,12,33], [], []], dtype=object)

In [8]:
m

array([list([123, 12, 123, 12, 33]), list([]), list([])], dtype=object)

In [9]:
type(m)

numpy.ndarray

In [11]:
import cv2

In [13]:
img_g = cv2.imread("smallgray.png",0) # 0 = grayscale #1 = bglight
img_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [14]:
img_g = cv2.imread("smallgray.png",1) # 0 = grayscale #1 = bglight
img_g

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [16]:
cv2.imwrite("newsmallgray.png", img_g)

True